version: '3'
services:
  web:
    image: pilyukovmp/web-api
    depends_on:
      - 'clientredis'
      - 'rabbitmq'
    ports:
      - '5002:80'
    links:
      - 'clientredis'
      - 'rabbitmq'

  async:
    image: pilyukovmp/async
    depends_on:
      - 'clientredis'
      - 'rabbitmq'    
    links:
      - 'clientredis'
      - 'rabbitmq'

  clientredis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - clientredis-data:/data
    ports:
      - '6379:6379'

  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: node.rabbit
    ports:
      - '4369:4369'
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
      - '35197:35197'
    environment:
      RABBITMQ_LOGS: /var/log/rabbitmq/rabbit.log
    restart: always
    volumes:
      - /data:/var/lib/rabbitmq
      - /data/logs:/var/log/rabbitmq
    
volumes:
  clientredis-data: